# Imagen base de Python
FROM nginx

# Copia los archivos de requerimientos al directorio de trabajo
COPY ./ /usr/share/nginx/html

# Exponemos el número de puerto de Nginx (80) para permitir la comunicación
EXPOSE 80
